# Generated by Django 6.0 on 2025-12-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', '帖子'), ('comment', '评论')], db_index=True, max_length=20, verbose_name='目标类型')),
                ('target_id', models.BigIntegerField(db_index=True, verbose_name='目标ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='likes_like_target__dd82ba_idx'), models.Index(fields=['user', '-created_at'], name='likes_like_user_id_222920_idx')],
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
    ]
