# Generated by Django 6.0 on 2025-12-13 07:50

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('role', models.CharField(choices=[('student', '普通学生用户'), ('merchant', '商户/广告用户'), ('moderator', '板块版主'), ('admin', '内容管理员'), ('superAdmin', '超级管理员')], db_index=True, default='student', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('active', '活跃状态'), ('banned', '封禁状态')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('reputation', models.IntegerField(default=100, verbose_name='信誉值')),
                ('post_count', models.IntegerField(default=0, verbose_name='发帖数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_active', models.BooleanField(default=True, help_text='指明用户是否可以登录', verbose_name='是否活跃')),
                ('is_staff', models.BooleanField(default=False, help_text='指明用户是否可以访问管理后台', verbose_name='是否是管理员')),
                ('is_superuser', models.BooleanField(default=False, help_text='指明用户是否拥有所有权限', verbose_name='是否是超级用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['status'], name='accounts_us_status_6bbe13_idx'), models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
