# Generated by Django 6.0 on 2025-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_follow',
            field=models.BooleanField(default=True, verbose_name='允许他人关注我'),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_messages',
            field=models.BooleanField(default=True, verbose_name='谁可以给我发送私信'),
        ),
        migrations.AddField(
            model_name='user',
            name='save_history',
            field=models.BooleanField(default=True, verbose_name='保存浏览历史'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_posts',
            field=models.BooleanField(default=True, verbose_name='谁可以查看我的帖子'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_profile',
            field=models.BooleanField(default=True, verbose_name='谁可以查看我的个人资料'),
        ),
    ]
