# Generated by Django 6.0 on 2025-12-14 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='消息主题')),
                ('content', models.TextField(max_length=2000, verbose_name='消息内容')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读')], db_index=True, default='unread', max_length=20, verbose_name='消息状态')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='user_messag_sender__ea3758_idx'), models.Index(fields=['recipient', 'status', '-created_at'], name='user_messag_recipie_9d8fca_idx'), models.Index(fields=['is_system', '-created_at'], name='user_messag_is_syst_16e4ca_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender__isnull', False), ('is_system', True), _connector='OR'), name='sender_or_system_constraint')],
            },
        ),
    ]
