# Generated by Django 6.0 on 2025-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='messages/images/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='messages/videos/', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='消息内容'),
        ),
    ]
