# Generated by Django 6.0 on 2025-12-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spam', '垃圾广告'), ('pornography', '色情内容'), ('violence', '暴力内容'), ('other', '其他违规内容')], db_index=True, max_length=20, verbose_name='举报类型')),
                ('reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='举报原因')),
                ('target_type', models.CharField(choices=[('post', '帖子'), ('comment', '评论')], db_index=True, max_length=20, verbose_name='目标类型')),
                ('target_id', models.BigIntegerField(db_index=True, verbose_name='目标ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理')], db_index=True, default='pending', max_length=20, verbose_name='处理状态')),
                ('action', models.CharField(blank=True, choices=[('ignore', '忽略'), ('delete', '删除内容'), ('warn', '警告用户')], max_length=20, null=True, verbose_name='处理动作')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='reports_rep_target__6b1f9a_idx'), models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'), models.Index(fields=['type', '-created_at'], name='reports_rep_type_a9e508_idx'), models.Index(fields=['reporter', '-created_at'], name='reports_rep_reporte_a9fa80_idx'), models.Index(fields=['processed_by', '-created_at'], name='reports_rep_process_1f6ed2_idx')],
            },
        ),
    ]
