# Generated by Django 6.0 on 2025-12-14 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', models.TextField(max_length=500, verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('like', '点赞通知'), ('comment', '评论通知'), ('follow', '关注通知'), ('report', '举报处理通知'), ('system', '系统通知'), ('admin', '管理员通知')], db_index=True, max_length=20, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读')], db_index=True, default='unread', max_length=20, verbose_name='通知状态')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content.comment', verbose_name='关联评论')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content.post', verbose_name='关联帖子')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='notificatio_recipie_1b3d03_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'), models.Index(fields=['sender', '-created_at'], name='notificatio_sender__3cf03f_idx')],
            },
        ),
    ]
