# Generated by Django 6.0 on 2025-12-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='问题')),
                ('answer', models.TextField(max_length=2000, verbose_name='答案')),
                ('question_type', models.CharField(choices=[('academic', '学习学术'), ('campus_life', '校园生活'), ('administration', '行政管理'), ('other', '其他')], db_index=True, default='other', max_length=20, verbose_name='问题类型')),
                ('keywords', models.JSONField(default=list, help_text='用于匹配用户问题的关键词列表', verbose_name='关键词')),
                ('weight', models.FloatField(default=1.0, help_text='匹配权重，值越高越优先匹配', verbose_name='匹配权重')),
                ('popularity', models.IntegerField(default=0, help_text='被访问次数', verbose_name='热度')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用该知识库条目', verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库条目',
                'verbose_name_plural': '知识库',
                'ordering': ['-weight', '-popularity'],
            },
        ),
        migrations.CreateModel(
            name='AIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(max_length=1000, verbose_name='用户输入')),
                ('ai_response', models.TextField(blank=True, max_length=2000, null=True, verbose_name='AI响应')),
                ('response_type', models.CharField(choices=[('knowledge_base', '知识库匹配'), ('ai_generated', 'AI生成'), ('error', '错误响应')], default='knowledge_base', max_length=20, verbose_name='响应类型')),
                ('similarity_score', models.FloatField(blank=True, help_text='用户输入与知识库条目的相似度', null=True, verbose_name='相似度分数')),
                ('processing_time', models.IntegerField(blank=True, help_text='AI处理响应的时间（毫秒）', null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_logs', to='ai_assistant.knowledgebase', verbose_name='匹配的知识库条目')),
            ],
            options={
                'verbose_name': 'AI响应日志',
                'verbose_name_plural': 'AI响应日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
