# Generated by Django 6.0 on 2025-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponselog',
            name='response_type',
            field=models.CharField(choices=[('knowledge_base', '知识库匹配'), ('post_based', '帖子匹配'), ('ai_generated', 'AI生成'), ('error', '错误响应')], default='knowledge_base', max_length=20, verbose_name='响应类型'),
        ),
    ]
