# Generated by Django 6.0 on 2025-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('value', models.JSONField(default=dict, verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI审核配置',
                'verbose_name_plural': 'AI审核配置',
            },
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='审核对象ID')),
                ('audit_type', models.CharField(choices=[('post', '帖子审核'), ('comment', '评论审核')], db_index=True, max_length=20, verbose_name='审核类型')),
                ('violation_type', models.CharField(choices=[('none', '无违规'), ('pornography', '色情内容'), ('violence', '暴力内容'), ('advertisement', '广告内容'), ('abuse', '辱骂内容'), ('sensitive', '敏感内容'), ('other', '其他违规')], default='none', max_length=20, verbose_name='违规类型')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('has_violation', models.BooleanField(default=False, verbose_name='是否违规')),
                ('sensitive_words', models.JSONField(blank=True, default=list, null=True, verbose_name='检测到的敏感词')),
                ('violation_reason', models.TextField(blank=True, null=True, verbose_name='违规原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': 'AI审核结果',
                'verbose_name_plural': 'AI审核结果',
                'indexes': [models.Index(fields=['object_id', 'audit_type'], name='ai_audit_au_object__72380e_idx'), models.Index(fields=['has_violation', 'created_at'], name='ai_audit_au_has_vio_ea9eaa_idx'), models.Index(fields=['violation_type', 'created_at'], name='ai_audit_au_violati_75f0b0_idx')],
            },
        ),
    ]
