# Generated by Django 6.0 on 2025-12-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='板块名称')),
                ('description', models.TextField(max_length=500, verbose_name='板块描述')),
                ('icon', models.CharField(default='default', max_length=50, verbose_name='板块图标')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='板块颜色')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数量')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='帖子标题')),
                ('content', models.TextField(max_length=10000, verbose_name='帖子内容')),
                ('type', models.CharField(choices=[('normal', '普通帖子'), ('trade', '二手交易帖子'), ('advertisement', '广告帖子')], db_index=True, default='normal', max_length=20, verbose_name='帖子类型')),
                ('images', models.JSONField(blank=True, default=list, null=True, verbose_name='图片URL数组')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('is_sticky', models.BooleanField(db_index=True, default=False, verbose_name='是否置顶')),
                ('is_essential', models.BooleanField(db_index=True, default=False, verbose_name='是否精华')),
                ('status', models.CharField(choices=[('normal', '正常状态'), ('deleted', '已删除'), ('reported', '已举报')], db_index=True, default='normal', max_length=20, verbose_name='帖子状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.category', verbose_name='所属板块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-is_sticky', '-is_essential', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('status', models.CharField(choices=[('normal', '正常状态'), ('deleted', '已删除'), ('reported', '已举报')], db_index=True, default='normal', max_length=20, verbose_name='评论状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='content_pos_categor_e17d13_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='content_pos_user_id_79b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['type', '-created_at'], name='content_pos_type_56a90c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_sticky', '-is_essential', '-created_at'], name='content_pos_is_stic_0cc104_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='content_com_post_id_66d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='content_com_user_id_316703_idx'),
        ),
    ]
