# Generated by Django 6.0 on 2025-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='媒体文件URL数组'),
        ),
    ]
