# Generated by Django 6.0 on 2025-12-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_post_images_post_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('normal', '普通帖子'), ('trade', '二手交易帖子'), ('advertisement', '广告帖子'), ('anonymous', '匿名帖子')], db_index=True, default='normal', max_length=20, verbose_name='帖子类型'),
        ),
    ]
