# Generated by Django 6.0 on 2025-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('normal', '正常状态'), ('deleted', '已删除'), ('reported', '已举报'), ('hidden', '隐藏')], db_index=True, default='normal', max_length=20, verbose_name='帖子状态'),
        ),
    ]
