# Generated by Django 6.0 on 2025-12-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='标签描述')),
                ('post_count', models.IntegerField(default=0, verbose_name='关联帖子数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='content.post', verbose_name='帖子')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_relations', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '帖子标签关系',
                'verbose_name_plural': '帖子标签关系',
                'indexes': [models.Index(fields=['post'], name='tags_postta_post_id_07711c_idx'), models.Index(fields=['tag'], name='tags_postta_tag_id_7040ae_idx')],
                'unique_together': {('post', 'tag')},
            },
        ),
    ]
