# Generated by Django 6.0 on 2025-12-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='广告标题')),
                ('content', models.TextField(max_length=5000, verbose_name='广告内容')),
                ('images', models.JSONField(blank=True, default=list, null=True, verbose_name='广告图片')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='广告链接')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '已发布'), ('rejected', '已拒绝'), ('expired', '已过期')], db_index=True, default='pending', max_length=20, verbose_name='广告状态')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('review_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='发布商户')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ads_adverti_status_961e72_idx'), models.Index(fields=['merchant', '-created_at'], name='ads_adverti_merchan_8a307e_idx'), models.Index(fields=['start_date', 'end_date'], name='ads_adverti_start_d_c0bb0c_idx')],
            },
        ),
    ]
