# Generated by Django 6.0 on 2025-12-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='规则的唯一名称', max_length=100, unique=True, verbose_name='规则名称')),
                ('type', models.CharField(choices=[('increase', '积分增加'), ('decrease', '积分减少')], help_text='积分增加或减少', max_length=20, verbose_name='规则类型')),
                ('event', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('create_post', '发帖'), ('create_comment', '评论'), ('like_post', '点赞帖子'), ('get_liked', '帖子被点赞'), ('get_commented', '帖子被评论'), ('report', '举报'), ('report_handled', '举报被处理'), ('other', '其他')], help_text='触发积分变动的事件', max_length=20, verbose_name='触发事件')),
                ('points', models.IntegerField(help_text='每次触发事件的积分变动数量', verbose_name='积分数量')),
                ('daily_limit', models.IntegerField(default=0, help_text='每日该规则可获取的最大积分，0表示无上限', verbose_name='每日上限')),
                ('total_limit', models.IntegerField(default=0, help_text='该规则可获取的总最大积分，0表示无上限', verbose_name='总上限')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用该规则', verbose_name='是否启用')),
                ('description', models.TextField(blank=True, help_text='规则的详细描述', max_length=500, verbose_name='规则描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分规则',
                'verbose_name_plural': '积分规则',
                'ordering': ['-is_enabled', 'event'],
            },
        ),
        migrations.CreateModel(
            name='PointsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True, default=0, help_text='用户当前可用积分', verbose_name='当前积分')),
                ('level', models.IntegerField(default=1, help_text='根据积分计算的用户等级', verbose_name='积分等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_info', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户积分信息',
                'verbose_name_plural': '用户积分信息',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('increase', '积分增加'), ('decrease', '积分减少')], db_index=True, max_length=20, verbose_name='记录类型')),
                ('amount', models.IntegerField(help_text='积分变动数量', verbose_name='积分数量')),
                ('balance', models.IntegerField(help_text='积分变动后的用户积分余额', verbose_name='变动后余额')),
                ('reason', models.CharField(help_text='积分变动的原因说明', max_length=200, verbose_name='变动原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_points_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_records', to='points.pointsrule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
